### ISSUE TITLE
This util destroy RAM

### ISSUE THREAD

**Issue by ghost** [mitranim/gow#10]
Util is nice, fast and easy-to-use, but after 200+ reloads it eating my RAM aggressively((( What can I help you?...

**Comment by mitranim** [comment]
Would appreciate more details. `gow` itself is unlikely to have a memory leak, but I'll keep an eye out now. When using `gow run`, it's expected to spawn one `go` subprocess, which in turn spawns another subprocess for the actual program. On each restart, the entire subprocess group should be killed. However, it's probably possible for the user program to spawn subprocesses in a way that would "leak" them, so without any other information, I would suggest checking for that.

**Comment by schlauerlauer** [comment]
I've noticed this aswell, it drops immediately when stopping gow and deleting `/tmp/go-build*`.
So maybe the old build processes are still running somehow?

**Comment by mitranim** [comment]
If you can reproduce excessive RAM usage, I would appreciate more details since I've been unable to. Most importantly: if you display your active processes as a tree, can you observe more than one immediate child process under `gow`, and can you observe "leaked"/daemonized processes orphaned after killing `gow`? In my understanding, this would be the only way for `gow` to leak anything. `gow` is carefully written to avoid such scenarios. On Unix, it spawns subprocesses in a group, and always terminates the entire subprocess group when restarting or just before its own termination. On Windows, this would require access to the "job object" API which is not provided/exposed by the Go standard library, and this is the main reason `gow` currently does not support Windows, as I'm not willing to provide a tool with known leakage potential. In any case, please report such details if you're able to observe them, or anything else pertinent. Thanks!

**Comment by schlauerlauer** [comment]
Sorry for not responding.
In my case it was not a memory leak but my `/tmp` directory is on a tmpfs.
So every file in `/tmp` is kept in RAM.
Cleaning up the old `go-builds` files would solve this issue.
