### ISSUE TITLE
using this tool with a cmd directory?

### ISSUE THREAD

**Issue by andersarpi** [mitranim/gow#16]
Hi,

I find I can't utilize gow well in a directory structure like this:

```
├── cmd
│   └── myapp
│       ├── .env
│       └── main.go
├── db
│   └── store
│       ├── dataset.go
│       └── store.go
├── go.mod
├── go.sum
```

I have to run `gow` inside the `/cmd/myapp` directory since the `.env` file has to be utilized. But I want the watch to trigger on changes to files in e.g. the `/db/` directory.

I can't find any commandline flag to specify paths to check.

Am I missing something, or is this simply not a feature currently provided?

Thanks for a great tool!

**Comment by mitranim** [comment]
Gow currently watches `./...` and assumes that all relevant files are in the CWD. It never occurred to me to provide an option to watch anything else, because...

You can simply run a folder from the repo root:

```sh
gow -c -v run ./some-folder
```

The `.env` file should also be in the root. Using any other CWD creates all sorts of headaches.

This approach does have a weakness: `go test` changes the CWD, so your tests will fail to load `.env` or any other assets relative to the repo root. I use `os.Chdir("..")` to fix that, by putting [the following](https://gist.github.com/mitranim/1ecfbc8c853e28969ae60c7838ab5a93) into a submodule and importing that module in `main_test.go`. I think it's better than dealing with different CWDs.

On an unrelated note, I recommend against modularizing Go apps. Modules are for libraries, and create nothing but headaches for apps. Of course I could be missing some viable use cases. But this is not pertinent to the issue at hand.

Glad you're finding the tool useful. 🙂

**Comment by andersarpi** [comment]
Thank you! That definitely solves my use case.
