### ISSUE TITLE
Is it possible to watch non go file ?

### ISSUE THREAD

**Issue by EmrysMyrddin** [mitranim/gow#2]
In my project, I have some configuration file which should trigger a restart of my go server. Is this possible with your tool ?

**Comment by mitranim** [comment]
Apologies for the late response.

I have a similar use case: I'd like a certain app to restart when changing `.env.properties`. Problem is, I don't know how to add this without overcomplicating the API. Currently, `gow` is dead simple to use, with good defaults and no configuration. We definitely don't want to restart on changes to _any_ file, which means the user has to specify a filter. Doing this on the command line every time would be fiddly to type and hard to remember. Which leads to something like configuration files, which I'd really like to avoid. Suggestions are welcome.

**Comment by Christopotamus** [comment]
Just started using this for a project and am really liking how simple it is, but I find myself needing to have it watch html files as well. Currently, I'm just re-saving one of my go files everytime I change an html file to trigger the reload, but it would be great if I could specify which file extensions to watch for in addition to .go files.

How about a simple yml file with a super simple format like:

```
extensions:
   - html
   - css
```

If you wanted to add it as a CLI option, it could be done via a simple flag with comma separated string of file extensions.

Resulting in a command like this:
`gow --extensions=html,css run .`

**Comment by mitranim** [comment]
Hey sorry for the delay. Still thinking about it.

The thing is, for HTML and text templates you don't really want to rebuild the server; you want to reload only the templates, which is _much_ faster. It needs some extra code, but once implemented, your development experience is much nicer.

Here's an excerpt from one of my apps: https://gist.github.com/mitranim/1e358e51b75812d25f4fcba7262df1ac

**Comment by mitranim** [comment]
The mere fact that someone asked for this feature means that regardless if `gow` supports custom extensions, the readme should include information about watching and rebuilding templates, since it's such a common use case. It could at least explain the difference between restarting the app and reinitializing the templates, and link to the example above.

**Comment by Christopotamus** [comment]
I appreciate you taking the time to get back with an example. I've built things which reload on file notify events before, but in this instance I am making a conscious effort to leave that to the tools themselves and not add more unnecessary bloat to my code. In my particular case, these templates will NEVER change in production, so I cannot justify adding additional code to watch the files that could introduce bugs and other issues.

Modifying the program to support something only needed in development simply doesn't make sense for my particular program and I feel should be part of the development tool-set as it has no use in the actual production program itself.

HTML templates are just one example of the many types of files people may want to trigger a rebuild. For many people, restarting the app would be ideal, but rebuilding is acceptable due to the quick build times in general and would increase productivity, which I believe should be the goal in any tool we use.

I like gow and it's speed + simplicity vs other watchers, and I'm certainly not suggesting turning this into a task runner, but it's a very limited tool for me if it will only watch .go and .mod files, and any tool that picks up the slack left behind will likely also takeover the .go watching (but probably do a worse job of it)

**Comment by mitranim** [comment]
Thanks for the feedback. It absolutely makes sense to have this feature as a starting point. As an application grows, the developer(s) may want to invest into smarter template watching, but it's really handy if the watcher/runner supports it out of the box.

Just pushed f797a2baf20611242b2b4b67e40dac793028b46d which allows to specify extensions with `-e` and ignored paths with `-i`. Update with `go get -u github.com/mitranim/gow` and you should be good.

Please enjoy, and let me know if you run into any issues.

Something I only realized after pushing the update is that `-e` is a bit too special-case; instead of listing the extensions, it might be handier to specify glob-style patterns. Might consider replacing it in the future, if someone asks for that feature.

**Comment by Christopotamus** [comment]
Thanks @mitranim! I will give it a try today and let you know if I have any issues.

**Comment by mitranim** [comment]
Been using this for a while, haven't noticed any issues. 🙂 Closing for now.
