### ISSUE TITLE
Use a newline before recompile

### ISSUE THREAD

**Issue by cco3** [mitranim/gow#31]
It's visually difficult to tell where the old compile ended and the new compile began. A newline would be a simple way to address this, but colorization would also be an option.

I'm aware -c exists, but something default would be good.

**Comment by cco3** [comment]
I'm aware -c exists, but something default would be good.

**Comment by mitranim** [comment]
`-s` might be suitable.

**Comment by cco3** [comment]
That make sense; could that default to `\n`?

**Comment by mitranim** [comment]
Sorry I misspoke. I meant `-S`, but you might have guessed already. Anyway the default is an empty string which means no separator is written. If you specify a non-empty string, it will write it. I think minimal output is the best default. One of the reasons `gow` exists is because other similar runners are too verbose by default. Personal taste. In your case, you probably want something like:
```sh
gow -v -S=<separator> <command>
```
`-S` does support `\n`, converting that to LF.

**Comment by mitranim** [comment]
`-v` causes `gow` to log FS events and other causes of restart, which serves as kind of a separator. `-S` just lets you provide a bigger, more noticeable one. My preferred approach is `-c` which hard-clears the terminal on each restart, so you only see the latest output, and don't need any separators.

**Comment by cco3** [comment]
OK, thanks!

**Comment by mitranim** [comment]
Also see 2a0f02802c8cc0cee610bca0334c7d9ba354d498 which might improve your UX.
