### ISSUE TITLE
Hotkey to show hotkey help

### ISSUE THREAD

**Issue by tomasaschan** [mitranim/gow#34]
Several times in a long-running `gow` session, I've found myself forgetting all hotkeys except `^C` - even forgetting which ones are available. It would be nice if there was a way to show the hotkey help directly in the session, without having to open a separate terminal for `gow -h` (or open a browser to the readme).

I figured it would make sense to wire e.g. `^H` to that, and started reading code to prepare a PR, but looking at https://github.com/mitranim/gow/blob/e50a405cdbc4cf6b473b802311a2f2355259ccb8/gow_misc.go#L14-L29 I realized I don't know where to find out the "true" names or corresponding integer values for the hotkeys.

I think it'd be a pretty trivial change once that is figured out; basically, add a case [here](https://github.com/mitranim/gow/blob/master/gow_stdio.go#L63-L86) with a new helper method like [this one](https://github.com/mitranim/gow/blob/master/gow_stdio.go#L63-L86) that prints all of the hotkeys and what they do.

**Comment by mitranim** [comment]
When reading the terminal in raw mode, we receive "control" inputs in two ways: via single-byte ASCII control codes, and via ANSI escape sequences. Currently, `gow` interprets only ASCII control codes, which is why internally it uses a single-byte buffer, for simplicity. For example, `ctrl+r` in many terminals sends `0x12` which `gow` interprets as "restart", while `↑` sends `0x1b` `0x5b` `0x41` (`esc` `[` `a`). References: [ASCII](https://en.wikipedia.org/wiki/Ascii), [ANSI escapes](https://en.wikipedia.org/wiki/ANSI_escape_code). I just checked by logging in `gow`, and in my terminal, `ctrl+h` sends `0x7f` which is the ASCII delete character. This _might_ vary by terminal. I'm using the MacOS built-in one. If this is consistent between various terminal apps (or parent shells? haven't properly investigated how this works), then we could add a special case. Feel free to make a PR. 🙂

**Comment by tomasaschan** [comment]
Ah, nice! I'll see if I can get the same level of logging working to verify some other terminals (eg the vs code integrated one and Windows Terminal). Any hints on how you set this up are appreciated :)

Once I have that I'll probably put a PR together!

**Comment by mitranim** [comment]
You can log the buffer in `Stdio.Run`, or the byte in `Stdio.OnByte`, then check the byte against ASCII. If the byte is `0x1b`, you're seeing the beginning of an ANSI escape sequence which is continued in subsequent bytes. Changing the buffer to `[]byte` allows to read an entire escape sequence in raw mode, or an entire line in cooked mode. It's not currently implemented this way because `gow` doesn't need that, and I don't want to deal with the edge case of accidentally splitting an escape sequence or Unicode character across buffer boundaries.

**Comment by mitranim** [comment]
For hacking on `gow`, I typically run `gow -c -v install` in one tab (and leave it like this), and manually restart `gow` in another tab while working on the code. Restore the normal global executable later. Technically you can also run `gow` under `gow` (to any depth), but the resulting behavior is hard to predict so you'd spend more time trying to understand what's happening than actually hacking.
